# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c44c1ddc7b39dd7caeff02a2590ce7f1"
name = "ChargebackReady"
application_url = "https://chargebackready-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders"

[auth]
redirect_urls = [
  "https://chargebackready-production.up.railway.app/auth/callback",
  "https://chargebackready-production.up.railway.app/auth/shopify/callback",
  "https://chargebackready-production.up.railway.app/api/auth/callback",
  "https://admin.shopify.com/store/eleven45ventures/apps/chargebackready/app/auth/callback",
  "https://admin.shopify.com/store/eleven45ventures/apps/chargebackready/app/auth/shopify/callback",
  "https://admin.shopify.com/store/eleven45ventures/apps/chargebackready/app/api/auth/callback",
  "https://eleven45ventures.myshopify.com/admin/apps/chargeback-ready",
  "http://localhost:3457/auth/callback",
  "http://localhost:3457/auth/shopify/callback",
  "http://localhost:3457/api/auth/callback",
]

