import PDFDocument from "pdfkit";

const NAVY   = "#1e3a5f";
const TEAL   = "#0f766e";
const RED    = "#b91c1c";
const AMBER  = "#b45309";
const MUTED  = "#6b7280";
const TEXT   = "#111827";
const LIGHT  = "#f9fafb";
const BORDER = "#d1d5db";
const WHITE  = "#ffffff";
const BLUE   = "#1d4ed8";

const M    = 50;
const PW   = 612;
const CW   = PW - M * 2;
const FOOT = 48;   // space reserved at bottom for footer

// ─── Helpers ─────────────────────────────────────────────────────────────────

function drawFooter(doc) {
  const fy = doc.page.height - 38;
  doc.moveTo(50, fy - 12).lineTo(doc.page.width - 50, fy - 12)
     .strokeColor("#dddddd").lineWidth(0.5).stroke();
  doc.font("Helvetica").fontSize(8).fillColor(MUTED)
     .text("Generated by ChargebackReady | chargebackready.org", M, fy, { lineBreak: false });
  doc.font("Helvetica").fontSize(7.5).fillColor("#888888")
     .text("Confidential — for dispute resolution purposes only", M, fy + 14, { width: CW, align: "center" });
}

function newPage(doc) {
  drawFooter(doc);
  doc.addPage();
  doc.y = M + 10;
}

function needsPage(doc, h) {
  if (doc.y + h > doc.page.height - FOOT) newPage(doc);
}

function hRule(doc) {
  doc.moveTo(M, doc.y).lineTo(PW - M, doc.y)
     .strokeColor(BORDER).lineWidth(0.5).stroke();
}

function sectionBar(doc, label) {
  needsPage(doc, 110);
  const y = doc.y;
  doc.rect(M, y, CW, 26).fill(NAVY);
  doc.font("Helvetica-Bold").fontSize(10).fillColor(WHITE)
     .text(label, M + 12, y + 8, { lineBreak: false });
  doc.fillColor(TEXT);
  doc.y = y + 36;
}

function field(doc, label, value) {
  needsPage(doc, 18);
  const y = doc.y;
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor(MUTED)
     .text(label, M, y, { width: 148, lineBreak: false });
  doc.font("Helvetica").fontSize(10.5).fillColor(TEXT)
     .text(String(value ?? "—"), M + 155, y, { width: CW - 155 });
  if (doc.y < y + 16) doc.y = y + 16;
}

function gap(doc, n = 12) { doc.y += n; }

// ─── Content renderer ────────────────────────────────────────────────────────

function render(doc, evidence) {
  const caseHeader       = evidence?.caseHeader       ?? {};
  const transactionProof = evidence?.transactionProof ?? {};
  const customerIdentity = evidence?.customerIdentity ?? {};
  const deliveryProof    = evidence?.deliveryProof    ?? {};
  const orderContents    = evidence?.orderContents    ?? {};

  // ── Cover header ────────────────────────────────────────────────────────────
  doc.rect(0, 0, PW, 78).fill(NAVY);
  doc.font("Helvetica-Bold").fontSize(18).fillColor(WHITE)
     .text("CHARGEBACK DISPUTE EVIDENCE PACKAGE", M, 17, { align: "center", width: CW });
  doc.font("Helvetica").fontSize(9.5).fillColor("#93c5fd")
     .text(
       `Order ${caseHeader.orderNumber}  ·  ${caseHeader.orderDate}  ·  Generated ${caseHeader.generatedAt}`,
       M, 46, { align: "center", width: CW },
     );
  doc.fillColor(TEXT);
  doc.y = 96;

  // ── SECTION 1: TRANSACTION DETAILS ─────────────────────────────────────────
  sectionBar(doc, "SECTION 1 — TRANSACTION DETAILS");
  gap(doc, 4);

  field(doc, "Order Number",     caseHeader.orderNumber);
  field(doc, "Order Date",       caseHeader.orderDate);
  field(doc, "Charge Amount",    transactionProof.amount);
  field(doc, "Payment Gateway",  transactionProof.paymentGateway);
  field(doc, "AVS Verification", transactionProof.avsResult);
  field(doc, "CVV Verification", transactionProof.cvvResult);
  field(doc, "3D Secure",        transactionProof.threeDSecure);

  gap(doc, 14);
  needsPage(doc, 34);

  const riskLevel = transactionProof.riskLevel || "Not available";
  const riskColor =
    riskLevel === "High"   ? RED   :
    riskLevel === "Medium" ? AMBER : TEAL;
  const rby = doc.y;
  doc.rect(M, rby, CW, 28).fill(riskColor);
  doc.font("Helvetica-Bold").fontSize(11).fillColor(WHITE)
     .text(`RISK LEVEL: ${riskLevel.toUpperCase()}`, M, rby + 8,
       { align: "center", width: CW, lineBreak: false });
  doc.fillColor(TEXT);
  doc.y = rby + 36;

  const factors = transactionProof.riskFactors || [];
  if (factors.length > 0) {
    gap(doc, 8);
    needsPage(doc, 14 + factors.length * 15);
    doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED)
       .text("Risk Factors:", M, doc.y);
    doc.y += 5;
    for (const f of factors) {
      needsPage(doc, 16);
      doc.font("Helvetica").fontSize(10).fillColor(TEXT)
         .text(`•   ${f}`, M + 14, doc.y, { width: CW - 14 });
      doc.y += 2;
    }
  }

  gap(doc, 24);

  // ── SECTION 2: CUSTOMER IDENTITY ───────────────────────────────────────────
  sectionBar(doc, "SECTION 2 — CUSTOMER IDENTITY");
  gap(doc, 4);

  field(doc, "Full Name",      customerIdentity.fullName);
  field(doc, "Email Address",  customerIdentity.email);
  field(doc, "Phone Number",   customerIdentity.phone);
  field(doc, "IP Address",     customerIdentity.ipAddress);
  field(doc, "Customer Since", customerIdentity.customerSince);
  field(doc, "Total Orders",   String(customerIdentity.totalOrdersWithStore));
  field(doc, "Lifetime Spend", customerIdentity.totalLifetimeSpend);

  gap(doc, 16);

  // Addresses — side by side
  const ba = customerIdentity.billingAddress  ?? { line1: "Not provided", line2: "Not provided", city: "Not provided", province: "Not provided", zip: "Not provided", country: "Not provided" };
  const sa = customerIdentity.shippingAddress ?? { line1: "Not provided", line2: "Not provided", city: "Not provided", province: "Not provided", zip: "Not provided", country: "Not provided" };
  const addrLines = (a) =>
    [(a.line1 || "Not provided"),
     a.line2 && a.line2 !== "Not provided" ? a.line2 : null,
     `${a.city || "—"}, ${a.province || "—"} ${a.zip || "—"}`,
     (a.country || "Not provided")].filter(Boolean);

  const baL = addrLines(ba);
  const saL = addrLines(sa);
  const lineH = 15;
  const addrHeight = 20 + Math.max(baL.length, saL.length) * lineH + 12;

  needsPage(doc, addrHeight + 36);

  const col1 = M;
  const col2 = M + CW / 2 + 8;
  const colW = CW / 2 - 8;
  const addrTop = doc.y;

  doc.font("Helvetica-Bold").fontSize(9).fillColor(NAVY)
     .text("BILLING ADDRESS", col1, addrTop, { width: colW, lineBreak: false });
  doc.font("Helvetica-Bold").fontSize(9).fillColor(NAVY)
     .text("SHIPPING ADDRESS", col2, addrTop, { width: colW, lineBreak: false });
  doc.moveTo(col1, addrTop + 14).lineTo(col1 + colW, addrTop + 14)
     .strokeColor(NAVY).lineWidth(0.75).stroke();
  doc.moveTo(col2, addrTop + 14).lineTo(col2 + colW, addrTop + 14)
     .strokeColor(NAVY).lineWidth(0.75).stroke();

  doc.font("Helvetica").fontSize(10).fillColor(TEXT);
  let ay = addrTop + 20;
  for (const line of baL) {
    doc.text(line, col1, ay, { width: colW, lineBreak: false });
    ay += lineH;
  }
  ay = addrTop + 20;
  for (const line of saL) {
    doc.text(line, col2, ay, { width: colW, lineBreak: false });
    ay += lineH;
  }
  doc.y = addrTop + addrHeight;

  // Match/mismatch banner
  const matchColor = customerIdentity.addressesMatch ? TEAL : RED;
  const matchMsg   = customerIdentity.addressesMatch
    ? "✓   Billing and shipping addresses match"
    : "✗   Addresses do not match — review required";
  const mby = doc.y;
  doc.rect(M, mby, CW, 26).fill(matchColor);
  doc.font("Helvetica-Bold").fontSize(10.5).fillColor(WHITE)
     .text(matchMsg, M, mby + 7, { align: "center", width: CW, lineBreak: false });
  doc.fillColor(TEXT);
  doc.y = mby + 34;

  gap(doc, 28);

  // ── SECTION 3: DELIVERY & FULFILLMENT ──────────────────────────────────────
  sectionBar(doc, "SECTION 3 — DELIVERY & FULFILLMENT PROOF");
  gap(doc, 4);
  field(doc, "Fulfillment Status", deliveryProof.fulfillmentStatus);
  gap(doc, 10);

  if ((deliveryProof.trackingEntries ?? []).length === 0) {
    needsPage(doc, 18);
    doc.font("Helvetica-Oblique").fontSize(10).fillColor(MUTED)
       .text("No tracking information — order not yet fulfilled.", M, doc.y);
    doc.y += 20;
  } else {
    for (let i = 0; i < (deliveryProof.trackingEntries ?? []).length; i++) {
      const e = (deliveryProof.trackingEntries ?? [])[i];
      needsPage(doc, 74);
      const ey = doc.y;
      doc.rect(M, ey, CW, 66)
         .fill(i % 2 === 0 ? LIGHT : WHITE)
         .lineWidth(0.5).strokeColor(BORDER).stroke();
      doc.font("Helvetica-Bold").fontSize(10).fillColor(NAVY)
         .text(`Shipment ${i + 1}`, M + 12, ey + 8, { lineBreak: false });
      const lx = M + 12;
      const vx = M + 106;
      doc.font("Helvetica-Bold").fontSize(9.5).fillColor(MUTED);
      doc.text("Carrier:",    lx,       ey + 25, { lineBreak: false });
      doc.text("Tracking #:", lx,       ey + 40, { lineBreak: false });
      doc.text("Shipped:",    M + 280,  ey + 25, { lineBreak: false });
      doc.text("Status:",     M + 280,  ey + 40, { lineBreak: false });
      doc.font("Helvetica").fontSize(10).fillColor(TEXT);
      doc.text(e.carrier,        vx,      ey + 25, { width: 160, lineBreak: false });
      doc.text(e.trackingNumber, vx,      ey + 40, { width: 160, lineBreak: false });
      doc.text(e.shippedDate,    M + 344, ey + 25, { lineBreak: false });
      doc.text(e.status,         M + 344, ey + 40, { lineBreak: false });
      if (e.trackingUrl && e.trackingUrl !== "Not provided") {
        doc.font("Helvetica-Oblique").fontSize(8.5).fillColor(BLUE)
           .text(e.trackingUrl, lx, ey + 54, { width: CW - 24, lineBreak: false });
      }
      doc.y = ey + 74;
    }
  }

  gap(doc, 28);

  // ── SECTION 4: ITEMS ORDERED ─────────────────────────────────────────────
  sectionBar(doc, "SECTION 4 — ITEMS ORDERED");
  gap(doc, 4);

  needsPage(doc, 26);
  const th = doc.y;
  doc.rect(M, th, CW, 22).fill(NAVY);
  const c = { name: M + 6, variant: M + 192, qty: M + 312, unit: M + 358, total: M + 448 };
  doc.font("Helvetica-Bold").fontSize(9).fillColor(WHITE);
  doc.text("Product",    c.name,    th + 7, { lineBreak: false });
  doc.text("Variant",    c.variant, th + 7, { lineBreak: false });
  doc.text("Qty",        c.qty,     th + 7, { lineBreak: false });
  doc.text("Unit Price", c.unit,    th + 7, { lineBreak: false });
  doc.text("Total",      c.total,   th + 7, { lineBreak: false });
  doc.y = th + 24;

  if ((orderContents.lineItems ?? []).length === 0) {
    needsPage(doc, 20);
    doc.font("Helvetica-Oblique").fontSize(10).fillColor(MUTED)
       .text("No items recorded.", M + 6, doc.y);
    doc.y += 20;
  } else {
    for (let i = 0; i < (orderContents.lineItems ?? []).length; i++) {
      const item = (orderContents.lineItems ?? [])[i];
      needsPage(doc, 20);
      const ry = doc.y;
      doc.rect(M, ry, CW, 18).fill(i % 2 === 0 ? LIGHT : WHITE);
      doc.font("Helvetica").fontSize(10).fillColor(TEXT);
      doc.text(item.productName, c.name,    ry + 4, { width: 182, lineBreak: false });
      doc.text(item.variantName, c.variant, ry + 4, { width: 114, lineBreak: false });
      doc.text(String(item.quantity), c.qty, ry + 4, { lineBreak: false });
      doc.text(item.unitPrice,   c.unit,    ry + 4, { lineBreak: false });
      doc.text(item.totalPrice,  c.total,   ry + 4, { lineBreak: false });
      doc.y = ry + 20;
    }
  }

  gap(doc, 16);

  needsPage(doc, 56);
  doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED)
     .text("Customer Note:", M, doc.y);
  doc.y += 6;
  const ny = doc.y;
  doc.rect(M, ny, CW, 36).fill(LIGHT).lineWidth(0.5).strokeColor(BORDER).stroke();
  doc.font("Helvetica").fontSize(10).fillColor(TEXT)
     .text(orderContents.customerNote || "None provided", M + 12, ny + 10, { width: CW - 24 });
  doc.y = ny + 44;

  gap(doc, 16);
  if (doc.y + 20 <= doc.page.height - FOOT) {
    hRule(doc);
  }
}

// ─── Exported function ────────────────────────────────────────────────────────

export function generateChargebackPDF(evidence) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({
      margins: { top: M, left: M, right: M, bottom: 0 },
      size: "LETTER",
      autoFirstPage: true,
    });

    doc.on("data",  c => chunks.push(c));
    doc.on("error", reject);
    doc.on("end",   () => resolve(Buffer.concat(chunks)));

    render(doc, evidence);
    drawFooter(doc);   // footer on the final page
    doc.end();
  });
}
